# Generated by Django 5.1.3 on 2025-06-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, max_length=1024, null=True),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "message_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("admin_reply", models.TextField(blank=True, null=True)),
                ("admin_reply_date", models.DateTimeField(blank=True, null=True)),
                ("is_processed", models.BooleanField(default=False)),
            ],
        ),
    ]
