# Generated by Django 5.1.3 on 2025-06-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProfileAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("connections", models.IntegerField(blank=True, null=True)),
                ("account_type", models.CharField(default="normal", max_length=20)),
                ("account_age_years", models.FloatField(blank=True, null=True)),
                ("has_verification_shield", models.BooleanField(default=False)),
                ("has_custom_url", models.BooleanField(default=False)),
                ("has_profile_summary", models.BooleanField(default=False)),
                ("has_professional_photo", models.BooleanField(default=False)),
                ("has_old_photo", models.BooleanField(default=False)),
                ("outdated_job_info", models.BooleanField(default=False)),
                ("missing_about_or_education", models.BooleanField(default=False)),
                ("profile_completeness", models.BooleanField(default=False)),
                (
                    "skills_endorsements_count",
                    models.IntegerField(blank=True, null=True),
                ),
                ("has_recommendations", models.BooleanField(default=False)),
                ("personalized_profile", models.BooleanField(default=False)),
                ("recent_activity", models.BooleanField(default=False)),
                ("last_post_date", models.DateField(blank=True, null=True)),
                ("engagement_with_content", models.BooleanField(default=False)),
                ("engagement_history", models.BooleanField(default=False)),
                ("post_history_older_than_year", models.BooleanField(default=False)),
                ("profile_updates", models.BooleanField(default=False)),
                ("shared_interests", models.BooleanField(default=False)),
                ("open_to_networking", models.BooleanField(default=False)),
                ("industry_relevance", models.BooleanField(default=False)),
                ("active_job_titles", models.BooleanField(default=False)),
                ("newly_created", models.BooleanField(default=False)),
                ("sparse_job_history", models.BooleanField(default=False)),
                ("default_profile_picture", models.BooleanField(default=False)),
                ("low_connections", models.BooleanField(default=False)),
                ("no_engagement_on_posts", models.BooleanField(default=False)),
                ("score", models.IntegerField(default=0)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Profile Analysis",
                "verbose_name_plural": "Profile Analyses",
            },
        ),
    ]
